
[build]
  publish = "dist"
  functions = "functions"
  command = "npm run build"

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"

[[redirects]]
  from = "/demo"
  to = "/.netlify/functions/demo"